#!/bin/bash
# Execute all commands and daemons after X session started

#----- Daemons
    # Auto USB mounter
        udiskie -s &
    # Disale touchpad while typing on keyboard
        syndaemon -i 0.2 -d &
    # Redshift
        # Redshift needs a running geoclue agent to be able to query geoclue
            /usr/lib/geoclue-2.0/demos/agent &
        redshift-gtk &
    # Start VPN client and open VPN connection
        (sleep 10 ; /opt/piavpn/bin/pia-client) &
    # Use i3lock as screen saver
        xss-lock --transfer-sleep-lock -- i3exit lock &
    # Turn off screen (and lock screen) after 10 min of inactivity
        xset dpms 0 0 600
    # Restore wallpaper configuration and start windows compositor
        nitrogen --restore; sleep 1; picom -b
    # Bluetooth
        dbus-update-activation-environment DISPLAY; blueman-applet &

#----- Tray icons
    # Network manager with tray icon
        nm-applet 2>&1 /dev/null &
    # Pulse audio tray icon
        pasystray &

#----- Settings
    # Invert caps lock key and escape key
        setxkbmap -option caps:escape
    # Disable screen blanking when inactive
        xset -dpms & xset s noblank & xset s off

