%YAML 1.3
---
- Feature: THUMB WHEEL
- Rule:
  - TestBytes: [1, 2, 1, 127]
  - KeyPress:
    - Alt_L
    - depress
  - MouseScroll: [0, 1]
  - KeyPress:
    - Alt_L
    - release
  - Execute: [echo, right]
- Rule:
  - TestBytes: [1, 2, -128, -1]
  - KeyPress:
    - Alt_L
    - depress
  - MouseScroll: [0, -1]
  - KeyPress:
    - Alt_L
    - release
  - Execute: [echo, left]
...
