#!/bin/bash

# Start redshift if not already running. Stop it elsewise



REDSHIFT_START_CMD="redshift -o"
REDSHIFT_STOP_CMD="redshift -x"
FILE_TO_STORE_STATE="/tmp/redshift-state"


# Main function, takes no parameter
function main() {
    redshift_state=$(get_state)
    if [[ redshift_state -eq 0 ]]
    then
        start_redshift
    elif [[ redshift_state -eq 1 ]]
    then
        stop_redshift
    else
        echo "Error while reading value of global variable IS_REDSHIFT_RUNNING. Value is " ${IS_REDSHIFT_RUNNING} ".
        Expected 0 or 1. Please manually set its value to 0 or 1 to fix this issue."
        exit 1
    fi
}


# Start redshift
function start_redshift() {
    echo 1 > $FILE_TO_STORE_STATE
    ${REDSHIFT_START_CMD}
    notify-send "Redshift" "Redshift started"
}

# Stop redshift
function stop_redshift() {
    echo 0 > $FILE_TO_STORE_STATE
    ${REDSHIFT_STOP_CMD}
    notify-send "Redshift" "Redshift stopped"
}

# Get the current state of redshift
function get_state(){
    if [[ ! -f ${FILE_TO_STORE_STATE} ]]
    then
        echo 0
    else
        cat ${FILE_TO_STORE_STATE}
    fi
}

main
