#!/bin/bash


# Startup script to call at OS startup


#----- Daemons
    # Auto USB mounter
        /usr/bin/udiskie -s &
    # Disale touchpad while typing on keyboard
        syndaemon -i 0.2 -d &
    # Start pulseaudio
        (sleep 10 ; pulseaudio --start) &
    # Notifications daemon
        (sleep 15 ; dunst) &

#----- Tray icons
    # Network manager with tray icon
        nm-applet 2>&1 /dev/null &
    # Pulse audio tray icon
        pasystray &

#----- Settings
    # Invert caps lock key and escape key
        setxkbmap -option caps:escape
    # Disable screen blanking when inactive
        xset -dpms & xset s noblank & xset s off

# Initiate VPN connection
    (sleep 20 ; /opt/piavpn/bin/pia-client) &
